name: Simple CI

on:
  push:
    branches: [feature/login]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print a message
        run: |
          echo "âœ… This is a simple workflow."
          echo "Branch: ${{ github.ref_name }}"
